ConnectPeople/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='accounts/login/')),
    path('admin/', admin.site.urls),
    path('chatapp/', include('chatapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('groupchat/', include('groupchatapp.urls')),
]

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('index/', views.login_user, name='index'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup, name='signup')
]

chatapp/urls.py
from django.urls import path
from . import views

app_name = 'chatapp'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('chat/<int:sender_id>/<int:reciever_id>/messages', views.chatpage, name='chatpage'),
    path('chat/<int:sender_id>/<int:reciever_id>/delete-message/<int:message_id>/', views.delete_chat_message,
         name="delete_chat_message"),
    path('chat/chat-redirecter/<int:sender_id>/<int:chat_id>/', views.user_chat_redirecter,
         name='user_chat_redirecter'),
]

groupchatapp/urls.py
from django.urls import path
from . import views

app_name = 'groupchatapp'
urlpatterns = [
    path('', views.group_chat, name='group_chat'),
    path('<str:group_name>/<int:sender_id>/messages/', views.group_chat_messages, name='group_chat_messages'),
    path('create/', views.create_group, name='create_group'),
    path('delete/<str:group_name>/', views.delete_group, name='delete_group'),
    path('delete_group_message/<str:group_name>/<int:message_id>/', views.delete_group_message, name="delete_group_message"),
]

chatapp/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime

# Create your models here.
from django.db.models import Q


class Message(models.Model):
    msg_text = models.CharField(max_length=200, blank=False)
    send_time = models.DateTimeField(default=datetime.now)
    sender = models.ForeignKey(User, related_name='sender_user', on_delete=models.CASCADE)
    reciever = models.ForeignKey(User, related_name='reciever_user', on_delete=models.CASCADE)
    unread = models.BooleanField(default=True)

    def __str__(self):
        if len(self.msg_text) <= 30:
            return self.msg_text[:30]
        return self.msg_text[:30] + "..."

    @classmethod
    def create(cls, msg_text, sender, reciever):
        message = cls(msg_text=msg_text, sender=sender, reciever=reciever, unread=True)
        return message


class Chat(models.Model):
    latest_message = models.ForeignKey(Message, related_name='latest_message', on_delete=models.CASCADE)
    member_one = models.ForeignKey(User, related_name='member_one', on_delete=models.CASCADE)
    member_two = models.ForeignKey(User, related_name='member_two', on_delete=models.CASCADE)
    last_message_time = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.member_one.username

    def get_other_member(self, member):
        if self.member_one == member:
            return self.member_two
        else:
            return self.member_one

    def delete_latest_message(self):
        messages = Message.objects.filter((Q(sender=self.member_one) | Q(sender=self.member_two)),
                                          (Q(reciever=self.member_two) | Q(reciever=self.member_one))).order_by(
            '-send_time')
        if messages.count() > 1:
            updated_latest_message = messages[1]
            updated_chat = Chat.create(latest_message=updated_latest_message, member_one=self.member_one,
                                       member_two=self.member_two)
            updated_chat.save()
            self.delete()
        else:
            self.delete()

    @classmethod
    def create(cls, latest_message, member_one, member_two):
        chat = cls(latest_message=latest_message, member_one=member_one, member_two=member_two)
        return chat

    def update_latest_message(self, message):
        chat = Chat.create(latest_message=message, member_one=self.member_one, member_two=self.member_two)
        chat.save()
        self.delete()

chatapp/forms.py
from django import forms


class UserSearchForm(forms.Form):
    username = forms.CharField(label="User Name", max_length=50)


class MessageForm(forms.Form):
    message_text = forms.CharField(label="Enter message", max_length=50)

chatapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from .models import Message, Chat
from .decorators import user_can_see_chat, user_can_delete_message
from .forms import UserSearchForm, MessageForm


# Create your views here.
@method_decorator(login_required, name='dispatch')
class HomeView(View):
    def post(self, request):
        form = UserSearchForm(request.POST)
        if form.is_valid():
            try:
                user = User.objects.get(username=form.cleaned_data['username'])
                context = {'sender_id': request.user.pk, 'reciever_id': user.pk}
                return HttpResponseRedirect(reverse('chatapp:chatpage', kwargs=context))
            except User.DoesNotExist:
                form.add_error('username', ValidationError("User Doesn't Exist"))
        user_groups = request.user.group_members.all()
        return render(request, 'chatapp/home.html', {'form': form, 'user_groups': user_groups})

    def get(self, request):
        form = UserSearchForm()
        user_groups = request.user.group_members.all()
        user_chats =Chat.objects.filter(Q(member_one=request.user) | Q(member_two=request.user)).order_by(
            '-last_message_time')
        return render(request, 'chatapp/home.html',
                      {'form': form, 'user_groups': user_groups, 'user_chats': user_chats})


@login_required
@user_can_see_chat
def user_chat_redirecter(request, sender_id, chat_id):
    chat = Chat.objects.get(pk=chat_id)
    if chat.member_one.pk == sender_id:
        context = {'sender_id': sender_id, 'reciever_id': chat.member_two.pk}
    else:
        context = {'sender_id': sender_id, 'reciever_id': chat.member_one.pk}
    return HttpResponseRedirect(reverse('chatapp:chatpage', kwargs=context))


@login_required
@user_can_see_chat
def chatpage(request, sender_id, reciever_id):
    sender = User.objects.get(pk=sender_id)
    reciever = User.objects.get(pk=reciever_id)
    messages = Message.objects.filter((Q(sender=sender) | Q(sender=reciever)),
                                      (Q(reciever=reciever) | Q(reciever=sender))).order_by("send_time")
    unread_messages = Message.objects.filter(sender=reciever, reciever=sender, unread=True)
    for unread_message in unread_messages:
        unread_message.unread = False
        unread_message.save()

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message_text = form.cleaned_data['message_text']
            new_message = Message.create(msg_text=message_text, sender=sender, reciever=reciever)
            new_message.save()
            if not Chat.objects.filter(Q(member_one=sender) | Q(member_one=reciever),
                                       (Q(member_two=sender) | Q(member_two=reciever))).exists():
                chat = Chat.create(latest_message=new_message, member_one=sender, member_two=reciever)
                chat.save()
            else:
                chat = Chat.objects.get(Q(member_one=sender) | Q(member_one=reciever),
                                        (Q(member_two=sender) | Q(member_two=reciever)))
                chat.update_latest_message(new_message)

    form = MessageForm()
    context = {'sender': sender, 'reciever': reciever, 'messages': messages, 'form': form}
    return render(request, 'chatapp/chatpage.html', context)


@login_required
@user_can_delete_message
def delete_chat_message(request, sender_id, reciever_id, message_id):
    message = Message.objects.get(pk=message_id)
    if Chat.objects.filter(latest_message=message).exists():
        chat = Chat.objects.get(latest_message=message)
        chat.delete_latest_message()
    message.delete()
    context = {'sender_id': sender_id, 'reciever_id': reciever_id}
    return HttpResponseRedirect(reverse('chatapp:chatpage', kwargs=context))

chatapp/templates/chatapp/base.html
{%load static%}
{% load crispy_forms_tags %}
<link rel="stylesheet" type="text/css" href="{%static 'chatapp/css/bootstrap.css'%}">
<link rel="stylesheet" type="text/css" href="{%static 'chatapp/css/bootstrap.min.css'%}">
<link rel="stylesheet" type="text/css" href="{%static 'chatapp/css/stylesheet.css'%}">
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{%block title%}{%endblock title%}</title>
    </head>
    <body>
    <nav class="navbar navbar-expand navbar-light bg-light">
      <a class="navbar-brand" href="#">ConnectPeople</a>

        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{%url 'chatapp:home'%}">Home</a>
            {% if user.is_authenticated%}
                <a class="nav-item nav-link active" href="{%url 'accounts:logout'%}">Logout</a>
            {%else%}
                <a class="nav-item nav-link active" href="{% url 'accounts:login'%}">Login</a>
            {%endif%}
            <a class="nav-item nav-link" href="">Welcome {{user.username}}</a>
        </div>

    </nav>
    <div id="content" class=" d-flex-row justify-content-center">
        {%block content%}
        {%endblock content%}
    </div>
    </body>
</html>

chatapp/templates/chatapp/chatpage.html
{% extends 'chatapp/base.html'%}
{%block title%}Chat Page{%endblock title%}
{%block content%}

<div class="container">
    <div class="row">
        <div class="col text-left">
            {{reciever.username}}
        </div>
        <div class="col text-right">
            {{sender.username}}
        </div>
    </div>
    {%for message in messages%}
        <div class="row">
            {%if message.sender.id == sender.id%}
                <div class="col"></div>
                <div class="col text-right card text-black bg-light my-2" style="max-width: 22rem;">
                    <div class="card-body">
                        <p class="card-text">
                            {{message.msg_text}}
                        </p>
                    </div>
                    <div class="card-footer">
                        <small class="text-black">{{message.send_time}}</small>
                            {% if message.unread%}
                                <small class="text-black">Sent</small>
                            {% else %}
                                <small class="text-primary"> Read </small>
                            {% endif %}
                        <a class="btn btn-primary btn-sm"
                           href="{%url 'chatapp:delete_chat_message' message.sender_id message.reciever_id message.id%}">
                            Undo
                        </a>
                    </div>
                </div>
            {%else%}
                <div class="col text-left card text-black bg-light my-2" style="max-width: 18rem;">
                    <div class="card-body">
                        <p class="card-text">
                            {{message.msg_text}}
                        </p>
                    </div>
                    <div class="card-footer">
                        <small class="text-black">{{message.send_time}}</small>
                    </div>
                </div>
            {%endif%}
        </div>
    {% endfor %}
</div>
<form action="{% url 'chatapp:chatpage' sender.id reciever.id%}" method="post">
    {%csrf_token%}
    {{form}}
    <input type="submit" value="Send" class="btn btn-primary">
</form>
<form action="{%url 'chatapp:chatpage' sender.id reciever.id%}">
    <input type="submit" value="Refresh" class="btn btn-primary">
</form>
{%endblock content%}

chatapp/templates/chatapp/home.html
{%extends 'chatapp/base.html'%}
{%load crispy_forms_tags %}
{%load chats_extra %}
{%block title%}Home{%endblock title%}
{%block content%}
<div class="container" id="form_container">
    <div class="row">
        <div class="col-sm-3 "></div>
        <div class="col-sm">
            <form method="post" action="{% url 'chatapp:home' %}" class="d-flex-row form-inline">
                {%csrf_token%}
                {{form|crispy}}
                <input type="submit" class="btn btn-primary" value="Search">
            </form>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm list-group">
            <div class="list-group-item text-center">
                Your Chats:
            </div>
            {%for user_chat in user_chats%}
                    <a class="list-group-item list-group-item-action"
                       href="{%url 'chatapp:user_chat_redirecter' user.id user_chat.id %}">
                        <div class="container">
                            <div class="row">
                                <div class="col-auto">{% other_member user_chat user %} </div>
                                <div class="col text-primary">{{user_chat.latest_message}}</div>
                                <span class="col-auto badge badge-primary">{% unread_messages_count user_chat user %}</span>
                            </div>
                        </div>
                    </a>
            {%endfor%}
        </div>
        <div class="col-sm-3"></div>
    </div>


    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm list-group">
            <div class="list-group-item text-center">
                Your groups:
            </div>
            {%for user_group in user_groups%}
                <a class="list-group-item list-group-item-action text-primary"
                   href="{%url 'groupchatapp:group_chat_messages' user_group.group_name user.id%}">
                    <div class="container">
                        <div class="row">
                            <div class="col-auto">{{user_group.group_name}}</div>
                            <div class="col text-primary">{% latest_group_message_info user user_group %}</div>
                        </div>
                    </div>
                </a>
            {%endfor%}
        </div>
        <div class="col-sm-3"></div>
    </div>
    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm-8 text-center">For joining or creating new group</div>
        <div class="col-sm"></div>
    </div>
    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm-8">
            <form method="get" action="{%url 'groupchatapp:group_chat'%}" class="form-inline justify-content-center">
                <button type="submit" class="btn btn-primary text-center">For Group Chat</button>
            </form>
        </div>
        <div class="col-sm"></div>
    </div>
</div>
{%endblock content%}