ConnectPeople/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='accounts/login/')),
    path('admin/', admin.site.urls),
    path('chatapp/', include('chatapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('groupchat/', include('groupchatapp.urls')),
]

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('index/', views.login_user, name='index'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup, name='signup')
]

chatapp/urls.py
from django.urls import path
from . import views

app_name = 'chatapp'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('chat/<int:sender_id>/<int:reciever_id>/messages', views.chatpage, name='chatpage'),
    path('chat/<int:sender_id>/<int:reciever_id>/delete-message/<int:message_id>/', views.delete_chat_message,
         name="delete_chat_message"),
    path('chat/chat-redirecter/<int:sender_id>/<int:chat_id>/', views.user_chat_redirecter,
         name='user_chat_redirecter'),
]

groupchatapp/urls.py
from django.urls import path
from . import views

app_name = 'groupchatapp'
urlpatterns = [
    path('', views.group_chat, name='group_chat'),
    path('<str:group_name>/<int:sender_id>/messages/', views.group_chat_messages, name='group_chat_messages'),
    path('create/', views.create_group, name='create_group'),
    path('delete/<str:group_name>/', views.delete_group, name='delete_group'),
    path('delete_group_message/<str:group_name>/<int:message_id>/', views.delete_group_message, name="delete_group_message"),
]

groupchatapp/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models


class Group(models.Model):
    group_name = models.CharField(max_length=20, unique=True)
    members = models.ManyToManyField(User, related_name='group_members')
    group_code = models.CharField(max_length=100)
    max_group_size = models.IntegerField(default=5)
    admin = models.CharField(default='ugarg', max_length=50)

    def __str__(self):
        return self.group_name

    @classmethod
    def create(cls, group_name, group_code, admin):
        group = cls(group_name=group_name, group_code=group_code, admin=admin)
        return group

    def check_for_vacancy(self):
        if self.members.all().count() < self.max_group_size:
            return True
        else:
            return False


class GroupMessage(models.Model):
    message_text = models.CharField(max_length=500)
    send_time = models.DateTimeField(default=datetime.now)
    sender = models.ForeignKey(User, related_name='sender', on_delete=models.CASCADE)
    group = models.ForeignKey(Group, related_name='related_group', on_delete=models.CASCADE)
    read = models.BooleanField(default=False)

    def __str__(self):
        return self.message_text[:25]

    @classmethod
    def create(cls, message_text, sender, group):
        message = cls(message_text=message_text, sender=sender, group=group)
        return message

groupchatapp/forms.py
from django import forms


class MessageForm(forms.Form):
    message_text = forms.CharField(label="Enter message", max_length=500)


class GroupSearchForm(forms.Form):
    groupname = forms.CharField(label="Group Name", max_length=50)
    groupcode = forms.CharField(label="Group Code", max_length=50)


class GroupCreationForm(forms.Form):
    groupname = forms.CharField(label="Group Name", max_length=50)
    groupcode = forms.CharField(label="Group Code", max_length=50)

groupchatapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import GroupCreationForm, GroupSearchForm, MessageForm
from .models import Group, GroupMessage
from .decorators import user_is_group_member, user_is_group_admin, user_can_delete_group_message, \
    user_can_send_group_message


@login_required
def group_chat(request):
    if request.method == 'POST':
        form = GroupSearchForm(request.POST)
        if form.is_valid():
            try:
                group = Group.objects.get(group_name=form.cleaned_data['groupname'])
                group_code = form.cleaned_data['groupcode']
                if group_code == group.group_code and group.check_for_vacancy():
                    context = {'group_name': group.group_name, 'sender_id': request.user.id}
                    group.members.add(request.user)
                    return HttpResponseRedirect(reverse('groupchatapp:group_chat_messages', kwargs=context))
                if not group.check_for_vacancy():
                    form.add_error('groupname', ValidationError('Group is full'))
                else:
                    form.add_error('groupname', ValidationError('Wrong Credentials'))
            except Group.DoesNotExist:
                form.add_error('groupname', ValidationError("Group doesn't exist"))
        return render(request, 'groupchatapp/group_page.html', {'form': form})
    form = GroupSearchForm()
    return render(request, 'groupchatapp/group_page.html', {'form': form})


@login_required
@user_is_group_member
@user_can_send_group_message
def group_chat_messages(request, group_name, sender_id):
    group = Group.objects.get(group_name=group_name)
    sender = User.objects.get(pk=sender_id)
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message_txt = form.cleaned_data['message_text']
            message = GroupMessage.create(message_text=message_txt, sender=sender, group=group)
            message.save()
    form = MessageForm()
    group_messages = GroupMessage.objects.all().filter(group=group).order_by('send_time')
    context = {'group_name': group_name, 'sender_id': sender_id, 'messages': group_messages, 'form': form,
               'members': group.members.all(), 'admin': group.admin, 'group_code': group.group_code}
    return render(request, 'groupchatapp/group_chat.html', context)


@login_required
def create_group(request):
    if request.method == 'POST':
        form = GroupCreationForm(request.POST)
        if form.is_valid():
            group_name = form.cleaned_data['groupname']
            group_code = form.cleaned_data['groupcode']
            try:
                group = Group.objects.all().get(group_name=group_name)
                form.add_error('groupname', ValidationError('This group name is not available'))
                return render(request, 'chatapp/create_group_page.html', {'form': form})
            except Group.DoesNotExist:
                group = Group.create(group_name=group_name, group_code=group_code, admin=request.user.username)
                group.save()
                group.members.add(request.user)
                context = {'group_name': group_name, 'sender_id': request.user.id}
                return HttpResponseRedirect(reverse('groupchatapp:group_chat_messages', kwargs=context))
        return render(request, 'chatapp/create_group_page.html', {'form': form})
    form = GroupCreationForm()
    return render(request, 'groupchatapp/create_group_page.html', {'form': form})


@login_required
@user_is_group_admin
def delete_group(request, group_name):
    group = Group.objects.get(group_name=group_name)
    group.delete()
    return HttpResponseRedirect(reverse('chatapp:home'))


@login_required
@user_is_group_member
@user_can_delete_group_message
def delete_group_message(request, group_name, message_id):
    message = GroupMessage.objects.get(pk=message_id)
    message.delete()
    context = {'group_name': group_name, 'sender_id': request.user.id}
    return HttpResponseRedirect(reverse('groupchatapp:group_chat_messages', kwargs=context))

groupchatapp/templates/groupchatapp/base.html
{%load static%}
{% load crispy_forms_tags %}
<link rel="stylesheet" type="text/css" href="{%static 'chatapp/css/bootstrap.css'%}">
<link rel="stylesheet" type="text/css" href="{%static 'chatapp/css/bootstrap.min.css'%}">
<link rel="stylesheet" type="text/css" href="{%static 'chatapp/css/stylesheet.css'%}">
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{%block title%}{%endblock title%}</title>
    </head>
    <body>
    <nav class="navbar navbar-expand navbar-light bg-light">
      <a class="navbar-brand" href="#">ConnectPeople</a>

        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{%url 'chatapp:home'%}">Home</a>
            {% if user.is_authenticated%}
                <a class="nav-item nav-link active" href="{%url 'accounts:logout'%}">Logout</a>
            {%else%}
                <a class="nav-item nav-link active" href="{% url 'accounts:login'%}">Login</a>
            {%endif%}
            <a class="nav-item nav-link" href="">Welcome {{user.username}}</a>
        </div>

    </nav>
    <div id="content" class=" d-flex-row justify-content-center">
        {%block content%}
        {%endblock content%}
    </div>
    </body>
</html>

groupchatapp/templates/groupchatapp/create_group_page.html
{%extends 'groupchatapp/base.html'%}
{% load crispy_forms_tags %}
{%block title%}Home{%endblock title%}
{%block content%}
<div class="container " id="form_container">
    <div class="row ">
        <div class="col-sm"></div>
        <div class="col-sm-8">
            <form method="post" action="{% url 'groupchatapp:create_group' %}" class="d-flex-row justify-content-center ">
                {%csrf_token%}
                {{form|crispy}}
                <input type="submit" class="btn btn-primary" value="Create">
            </form>
        </div>
        <div class="col-sm"></div>
    </div>
</div>
{%endblock content%}

groupchatapp/templates/groupchatapp/group_chat.html
{%extends 'groupchatapp/base.html'%}
{%block title%}
Group Chat
{%endblock title%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-sm">
            {%for message in messages%}
                <div class="row">
                    {%if message.sender.id == sender_id%}
                        <div class="col"></div>
                        <div class="col text-right card bg-light text-black my-2">
                            <div class="card-header">{{message.sender.username}}</div>
                            <div class="card-body">
                                <p class="card-text">
                                    {{message.message_text}}
                                </p>
                            </div>
                            <div class="card-footer">
                                <small class="text-black">{{message.send_time}}</small>
                                <a class="btn btn-primary btn-sm"
                                   href="{% url 'groupchatapp:delete_group_message' message.group.group_name message.pk%}">
                                    Undo
                                </a>
                            </div>
                        </div>
                    {%else%}
                        <div class="col text-left card bg-light text-black my-2">
                            <div class="card-header">{{message.sender.username}}</div>
                            <div class="card-body">
                                <p class="card-text">
                                    {{message.message_text}}
                                </p>
                            </div>
                            <div class="card-footer">
                                <small class="text-black">{{message.send_time}}</small>
                            </div>
                        </div>
                        <div class="col"></div>
                    {%endif%}
                </div>
            {% endfor %}
        </div>
        <div class="col-sm-3">
            <div>
                {%if user.username == admin %}
                <form method="post" action="{%url 'groupchatapp:delete_group' group_name%}">
                    {%csrf_token%}
                    <input type="submit" value="Delete Group" class="btn btn-danger">
                </form>
                {%endif%}
            </div>
            <div class="list-group">
                <div class="text-center list-group-item">Group Name: {{group_name}}</div>
                <div class="text-center list-group-item">Group Code: {{group_code}}</div>
                <div class="text-center list-group-item">Members</div>
                {%for member in members%}
                    <div class="member-names text-center list-group-item">
                        {{member.username}}
                    </div>
                {%endfor%}
            </div>
        </div>
    </div>
</div>
<form action="{% url 'groupchatapp:group_chat_messages' group_name sender_id %}" method="post">
    {%csrf_token%}
    {{form}}
    <input type="submit" value="Send" class="btn btn-primary btn-md">
</form>
<form class="" action="{%url 'groupchatapp:group_chat_messages' group_name sender_id %}">
    <input type="submit" value="Refresh" class="btn btn-primary btn-sm">
</form>
{%endblock content%}

groupchatapp/templates/groupchatapp/group_page.html
{%extends 'groupchatapp/base.html'%}
{%load crispy_forms_tags %}
{%block title%}Group Page{%endblock title%}
{%block content%}
<div class="container " id="form_container">
    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm-8">
            <form action="{%url 'groupchatapp:group_chat'%}" method="post" class="d-flex-row justify-content-center">
                {%csrf_token%}
                {{form|crispy}}
                <input type="submit" class="btn btn-primary" value="Search">
            </form>
        </div>
        <div class="col-sm"></div>
    </div>
    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm-8">
            Make a new group
            <form method="get" action="{%url 'groupchatapp:create_group' %}">
                <input type="submit" class="btn btn-primary" value="Create new group">
            </form>
        </div>
        <div class="col-sm"></div>
    </div>
</div>
{%endblock content%}