ConnectPeople/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='accounts/login/')),
    path('admin/', admin.site.urls),
    path('chatapp/', include('chatapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('groupchat/', include('groupchatapp.urls')),
]

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('index/', views.login_user, name='index'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup, name='signup')
]

chatapp/urls.py
from django.urls import path
from . import views

app_name = 'chatapp'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('chat/<int:sender_id>/<int:reciever_id>/messages', views.chatpage, name='chatpage'),
    path('chat/<int:sender_id>/<int:reciever_id>/delete-message/<int:message_id>/', views.delete_chat_message,
         name="delete_chat_message"),
    path('chat/chat-redirecter/<int:sender_id>/<int:chat_id>/', views.user_chat_redirecter,
         name='user_chat_redirecter'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse


def login_user(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('chatapp:home'))
    else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('chatapp:home'))
            messages.add_message(request, messages.INFO, 'Wrong Credentials')
            return HttpResponseRedirect(reverse('accounts:login'))
        return render(request, 'registration/login.html')


def logout_user(request):
    logout(request)


def signup(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('chatapp:home'))
    else:
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data['username']
                password = form.cleaned_data['password1']
                user = authenticate(username=username, password=password)
                login(request, user)
                return HttpResponseRedirect(reverse('chatapp:home'))
            return render(request, 'accounts/signup.html', {'form': form})
        form = UserCreationForm()
        return render(request, 'accounts/signup.html', {'form': form})

accounts/templates/accounts/base.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{%static 'accounts/css/bootstrap.css'%}">
<link rel="stylesheet" type="text/css" href="{%static 'accounts/css/bootstrap.min.css'%}">
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{%block title%}{%endblock title%}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand navbar-light bg-light">
          <a class="navbar-brand" href="#">ConnectPeople</a>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{%url 'chatapp:home'%}">Home</a>
                {% if user.is_authenticated%}
                    <a class="nav-item nav-link active" href="{%url 'accounts:logout'%}">Logout</a>
                {%else%}
                    <a class="nav-item nav-link active" href="{% url 'accounts:login'%}">Login</a>
                {%endif%}
            </div>
          </div>
        </nav>
        {%block content%}
        {%endblock content%}
    </body>
</html>

accounts/templates/accounts/signup.html
{%extends 'accounts/base.html'%}
{% load crispy_forms_tags %}
{%block title%}SignUp{%endblock title%}
{%block content%}
<div class="container " id="form_container">
    <div class="row ">
        <div class="col-sm"></div>
        <div class="col-sm-8">
            <form method="post" action="{% url 'accounts:signup' %}" class="d-flex-row justify-content-center ">
                {%csrf_token%}
                {{form|crispy}}
                <input type="submit" class="btn btn-primary" value="SignUp">
            </form>
        </div>
        <div class="col-sm"></div>
    </div>
</div>
{%endblock content%}